### ISSUE TITLE
Usage without preshared key in key exchange

### ISSUE THREAD

**Issue by pepe** [janet-lang/jhydro#4]
Per `libhydroen` docs, it is possible to use key exchange without a preshared key, or better with it set to NULL. I was trying it with `jhydro`, but it is either not possible, or I do not know how to do it. Can you please tell me if it is possible with the current implementation, and if not if I can try to implement it?

**Comment by bakpakin** [comment]
Couldn't you just set your pre-shared key to a constant? I assume that would be functionally equivalent to setting it to NULL. If that is not ideal, we could allow a nil pre-shared key.

**Comment by pepe** [comment]
I definitely can set a constant. It just did not occur to me that way. Thanks.

**Comment by tionis** [comment]
I just discovered the same problem.
While a constant would work, the code becomes less readable and terse by this.  
Why not just follow the libhydrogen API and allow nil?

**Comment by pepe** [comment]
I guess it is up for PRign it :-).

Anyway, I think the preshared key is a better solution every time I use the API. If only for the environment's sake :-).

**Comment by tionis** [comment]
I decided on using a semi hard-coded pre-shared key.  
If I change my mind, I may PR it, let's see.
